version: "3.0"
services:
    mysql:
        image: mysql:8.0
        ports:
        - 3306:3306
        volumes:
        - /var/lib/mysql
        environment:
            MYSQL_DATABASE: web
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
    db-migrate:
        image: migrate/migrate:4
        volumes:
        - ./sql:/migrations
        environment:
            DB_URL: mysql://user:123456@tcp(mysql:3306)/web
    web-app:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
        - 8080:8080
        image: web-app
        depends_on:
        - mysql
        volumes:
          - ./:/go_web_be
        env_file:
        - .env