version: "3.0"
services:
  mysql:
    image: mysql:8.0
    ports:
    - 3306:3306
    volumes:
    - /var/lib/mysql
    environment:
      MYSQL_DATABASE: web
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
  web-app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
    - 8080:8080
    image: web-app
    depends_on:
      - mysql
    env_file:
      - ./app.env
    entrypoint: ["./wait-for-it.sh","mysql:3306","--timeout=60","--","/web-app","server"]