// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"go_web/api/usecase/user"
	"go_web/domain/repository"
	"go_web/domain/service"
	"go_web/domain/service/implement"
	"go_web/infra/repository/mysql"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initUserRepository(db *gorm.DB) repository.UserRepo {
	userRepo := mysql.NewUserRepo(db)
	return userRepo
}

func initUserService(db *gorm.DB) service.UserService {
	userRepo := mysql.NewUserRepo(db)
	userService := implement.NewUserService(userRepo)
	return userService
}

func initUcCreateUser(db *gorm.DB) user.CreateUser {
	userService := initUserService(db)
	createUser := user.NewCreateUser(db, userService)
	return createUser
}

func initUcUpdateUser(db *gorm.DB) user.UpdateUser {
	userService := initUserService(db)
	updateUser := user.NewUpdateUser(db, userService)
	return updateUser
}

func initUcDeleteUser(db *gorm.DB) user.DeleteUser {
	userService := initUserService(db)
	deleteUser := user.NewDeleteUser(db, userService)
	return deleteUser
}

func initUcGetUser(db *gorm.DB) user.GetUser {
	userService := initUserService(db)
	getUser := user.NewGetUser(db, userService)
	return getUser
}
