name: Run unit test
run-name: Run go unit test by ${{github.actor}} on branch ${{github.ref_name}}
on: [workflow_dispatch]
jobs:
  go_test:
    runs-on: ubuntu-22.04
    env:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: 123456
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      
      # - name: build docker
      #   run: docker-compose build

      - name: prepare migrate script
        run: |
          cp ./sql/dump.sql ./sql/21001231001_dump.up.sql
          echo '' > ./sql/dump.sql ./sql/21001231001_dump.down.sql
      - name: startup mysql
        run: docker-compose up -d mysql
      - name: wait until mysql is ready
        run: |
          chmod +x ./script/wait-for-it.sh
          ./script/wait-for-it.sh $DB_HOST:$DB_PORT --timeout=60 -- echo 'mysql is ready'
      - name: migrate & seed data
        run: |
          docker-compose run db-migrate -verbose -path=/migrations/ -database "mysql://$DB_USER:$DB_PASS@tcp($DB_HOST:$DB_PORT)/web" drop -f 
          docker-compose run db-migrate -verbose -path=/migrations/ -database "mysql://$DB_USER:$DB_PASS@tcp($DB_HOST:$DB_PORT)/web" up 
